# Generated by Django 5.0.9 on 2024-11-18 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chefs", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="bio",
            field=models.TextField(max_length=400),
        ),
    ]
