# Generated by Django 5.0.9 on 2024-11-14 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="recipe",
            name="title",
            field=models.CharField(default="Untitled Recipe", max_length=100),
        ),
    ]
