# Generated by Django 5.0.9 on 2024-11-14 21:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0003_remove_recipe_ingredients"),
    ]

    operations = [
        migrations.AddField(
            model_name="recipe",
            name="date",
            field=models.DateTimeField(
                auto_now_add=True,
                default=datetime.datetime(
                    2024, 11, 14, 21, 45, 23, 702592, tzinfo=datetime.timezone.utc
                ),
            ),
            preserve_default=False,
        ),
    ]
