# Generated by Django 5.0.9 on 2024-11-20 00:22

import django.db.models.deletion
import sorl.thumbnail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0006_alter_instruction_options_instruction_order"),
    ]

    operations = [
        migrations.AddField(
            model_name="recipe",
            name="image",
            field=sorl.thumbnail.fields.ImageField(
                default="https://dummyimage.com/700x350/dee2e6/6c757d.jpg",
                upload_to="media",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="ingredient",
            name="item",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="ingredient",
            name="recipe",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ingredients",
                to="recipes.recipe",
            ),
        ),
        migrations.AlterField(
            model_name="instruction",
            name="recipe",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="instructions",
                to="recipes.recipe",
            ),
        ),
    ]
