# Generated by Django 5.0.9 on 2024-11-21 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0007_recipe_image_alter_ingredient_item_and_more'),
        ('recipes', '0008_category_recipe_categories'),
    ]

    operations = [
    ]
