# Generated by Django 5.0.9 on 2024-11-21 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0009_merge_20241121_1828"),
        ("recipes", "0009_merge_20241121_1840"),
    ]

    operations = []
