# Generated by Django 5.0.9 on 2024-11-25 01:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0010_merge_20241121_1855"),
        ("recipes", "0011_alter_recipe_image_comment"),
    ]

    operations = []
