# Generated by Django 5.0.9 on 2024-11-25 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0012_merge_20241125_0148"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="rating",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
