# Generated by Django 5.0.9 on 2024-11-26 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0013_comment_rating"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="comment",
            name="rating",
        ),
    ]
